config/routes.rb
Rails.application.routes.draw do
  get 'pages/cheatsheets'
  get 'pages/javascript'
  get 'pages/html_css'
  get 'pages/ror'
  get 'download_md', to: "pages#download_md"

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/markdown_code.rb
class MarkdownCode < ApplicationRecord

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/markdown_codes_controller.rb
class MarkdownCodesController < ApplicationController
  before_action :set_markdown_code, only: %i[show edit update destroy]

  # GET /markdown_codes or /markdown_codes.json
  def index
    @markdown_codes = MarkdownCode.all
  end

  # GET /markdown_codes/1 or /markdown_codes/1.json
  def show; end

  # GET /markdown_codes/new
  def new
    @markdown_code = MarkdownCode.new
  end

  # GET /markdown_codes/1/edit
  def edit; end

  # POST /markdown_codes or /markdown_codes.json
  def create
    @markdown_code = MarkdownCode.new(markdown_code_params)

    respond_to do |format|
      if @markdown_code.save
        format.html { redirect_to markdown_code_url(@markdown_code), notice: 'Markdown code was successfully created.' }
        format.json { render :show, status: :created, location: @markdown_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @markdown_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markdown_codes/1 or /markdown_codes/1.json
  def update
    respond_to do |format|
      if @markdown_code.update(markdown_code_params)
        format.html { redirect_to markdown_code_url(@markdown_code), notice: 'Markdown code was successfully updated.' }
        format.json { render :show, status: :ok, location: @markdown_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @markdown_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markdown_codes/1 or /markdown_codes/1.json
  def destroy
    @markdown_code.destroy

    respond_to do |format|
      format.html { redirect_to markdown_codes_url, notice: 'Markdown code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_markdown_code
    @markdown_code = MarkdownCode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def markdown_code_params
    params.require(:markdown_code).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def cheatsheets; end

  def html_css; end

  def index; end

  def ror; end

  def javascript; end

  def download_md
    name = params[:name]
    send_file "#{Rails.root}/public/docs/#{name}", type: 'application/md', x_sendfile: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'

  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  def markdown(text)
    return '' if text.nil?

    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      prettify: true
    }

    extensions = {
      autolink: true,
      tables: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
      disable_indented_code_blocks: true,
    }

    # Redcarpet::Markdown.new(HTML.new(options), extensions).render(text).html_safe
    # these 3 lines do same as above 1 line
    renderer = HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/markdown_codes_helper.rb
module MarkdownCodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark shadow">
  <div class="container-fluid">
    <%= link_to image_tag("Logo.svg", size: "50x50"), root_path, data: { turbo: false }, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Share's", root_path, class: "nav-link shares" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Secciones
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li class="d-flex">
              <%= link_to pages_ror_path, class: "dropdown-item" do %>
                <%= image_tag "diamante.svg", size: "25x25" %>
                Ruby on Rails
              <% end %>
            </li>
            <li class="d-flex">
              <%= link_to pages_html_css_path, class: "dropdown-item" do %>
                <%= image_tag "html.svg", size: "25x25" %>
                HTML
              <% end %>
            </li>
            <li class="d-flex">
              <%= link_to pages_html_css_path, class: "dropdown-item" do %>
                <%= image_tag "css.svg", size: "25x25" %>
                CSS
              <% end %>
            </li>
            <li class="d-flex">
              <%= link_to pages_html_css_path, class: "dropdown-item" do %>
                <%= image_tag "js.svg", size: "25x25" %>
                JavaScript
              <% end %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li class="d-flex">
              <%= link_to pages_javascript_path, class: "dropdown-item" do %>
                <%= image_tag "cheet.svg", size: "25x25" %>
                Cheat-Sheets
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareLinks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;900&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <main class="container mt-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/markdown_codes/_form.html.erb
<%= form_with(model: markdown_code) do |form| %>
  <% if markdown_code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(markdown_code.errors.count, "error") %> prohibited this markdown_code from being saved:</h2>

      <ul>
        <% markdown_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/markdown_codes/_markdown_code.html.erb
<div id="<%= dom_id markdown_code %>">
  <p>
    <strong>Content:</strong>
    <%= markdown(markdown_code.content) %>
  </p>
</div>

app/views/markdown_codes/edit.html.erb
<h1>Editing markdown code</h1>

<%= render "form", markdown_code: @markdown_code %>

<br>

<div>
  <%= link_to "Show this markdown code", @markdown_code %> |
  <%= link_to "Back to markdown codes", markdown_codes_path %>
</div>

app/views/markdown_codes/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Markdown codes</h1>
<div id="markdown_codes">
  <% @markdown_codes.each do |markdown_code| %>
    <%= render markdown_code %>
    <p>
      <%= link_to "Show this markdown code", markdown_code %>
    </p>
  <% end %>
</div>
<%= link_to "New markdown code", new_markdown_code_path %>

app/views/markdown_codes/new.html.erb
<h1>New markdown code</h1>

<%= render "form", markdown_code: @markdown_code %>

<br>

<div>
  <%= link_to "Back to markdown codes", markdown_codes_path %>
</div>

app/views/markdown_codes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @markdown_code %>

<div>
  <%= link_to "Edit this markdown code", edit_markdown_code_path(@markdown_code) %> |
  <%= link_to "Back to markdown codes", markdown_codes_path %>

  <%= button_to "Destroy this markdown code", @markdown_code, method: :delete %>
</div>

app/views/pages/cheatsheets.html.erb
<h1>Pages#cheetsheets</h1>
<p>Find me in app/views/pages/cheetsheets.html.erb</p>
<section class="sheets_container">
  <article class="php_sheet">
    <h2>
      PHP Cheatsheet
    </h2>
    <%= link_to download_md_path(name: "BraisonCrece_PHP_cheat_sheet.MD") do %>
      <%= image_tag "php.svg" %>
    <% end %>
  </article>
  <article class="css_sheet">
    <h2>
      CSS Cheatsheet
    </h2>
    <%= link_to download_md_path(name: "CSS_cheet-sheet.md") do %>
      <%= image_tag "CSS.svg" %>
    <% end %>
  </section>

app/views/pages/index.html.erb
<article>
  <h1 class="d-flex align-items-end">Bienvenido a  Share's! <span><%= image_tag "confeti.svg", size: "75x75", id: "confeti" %></span></h1>
  <p>En Share's podrás encontrar cientos de recursos gratuítos para aprender Desarrollo Web!</p>
  <h2>Recursos</h2>
  <!-- galería de tarjetas con las opciones -->
  <div class="row">
    <div class="col-md-6 col-sm-12 col-lg-4">
      <%= link_to pages_ror_path do %>
        <div class="card mb-3 ">
          <div class="card_img">
            <%= image_tag "RoR.svg" %>
          </div>
          <div class="card-body">
            <h5 class="card-title">Ruby on Rails</h5>
            <p class="card-text">
              Recopilación de recursos ,documentación y canales de youtube para aprender Ruby on Rails. 
              Además de toda la documentación oficial se Ruby y Rails!
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 col-sm-12 col-lg-4">
      <%= link_to pages_html_css_path do %>
        <div class="card mb-3">
          <div class="card_img">
            <%= image_tag "html_css_2.svg" %>
          </div>
          <div class="card-body">
            <h5 class="card-title">HTML & CSS</h5>
            <p class="card-text">
              Recopilación de recursos y tutoriales para aprender HTML y CSS. Desde lo más básico hasta lo más avanzado.
              Con ejemplos prácticos y ejercicios.
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 col-sm-12 col-lg-4">
      <%= link_to pages_cheatsheets_path do %>
        <div class="card mb-3">
          <div class="card_img">
            <%= image_tag "JS.svg" %>
          </div>
          <div class="card-body">
            <h5 class="card-title">JavaScript</h5>
            <p class="card-text">
              Recopilación de recursos y documentación para aprender JavaScript. 
              Con ejemplos prácticos y ejercicios.
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 col-sm-12 col-lg-4">
      <%= link_to pages_cheatsheets_path do %>
        <div class="card mb-3">
          <div class="card_img">
            <%= image_tag "cheat-sheet.png" %>
          </div>
          <div class="card-body d-block mt-5">
            <h5 class="card-title">Cheat-Sheets</h5>
            <p class="card-text">
              Recopilación de cheat-sheets de diferentes lenguajes de programación. Ideal para tener a mano en el escritorio.
              Opcion descargable en PDF y MarkDown.
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</article>

app/views/pages/javascript.html.erb
<h1>Pages#recursos</h1>
<p>Find me in app/views/pages/recursos.html.erb</p>

app/views/pages/recursos.html.erb
<h1>Pages#recursos</h1>
<p>Find me in app/views/pages/recursos.html.erb</p>

app/views/pages/ror.html.erb
<h2>Documentación Oficial</h2>
<ul class="lista_links_ROR mt-5 mb-5">
  <li class="d-flex">
    <%= link_to "https://guides.rubyonrails.org/", target: "_blank" do %>
      <%= image_tag  "RoR.svg", size: "75x75", class: "me-2"%>
    <%end%>
    <div>
      <%= link_to "Ruby on Rails guides", "https://guides.rubyonrails.org/", target: "_blank" %>
      <p>
        Rails Guides es un must para cualquier desarrollador que trabaje con Ruby on Rails.
        En este sitio encontrarás una gran cantidad de <code>información sobre el framework</code>. Además
        está disponible en varios idiomas, y es fácil de navegar.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://api.rubyonrails.org/", target: "_blank" do %>
      <%= image_tag  "RoR.svg", size: "75x75", class: "me-2"%>
    <%end%>
    <div>
      <%= link_to "Ruby on Rails api", "https://api.rubyonrails.org/", target: "_blank" %>
      <p>
        Esta es la documentación oficial de la <code>API de Ruby on Rails</code>. En este recurso encontrarás
        todos los métodos y clases que puedes utilizar en tu proyecto. Además, puedes buscar por
        palabras clave para encontrar la información que necesitas.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://rubyapi.org/", target: "_blank" do %>
      <%= image_tag  "ruby.svg", size: "75x75", class: "me-2"%>
    <%end%>
    <div>
      <%= link_to "API Ruby", "https://rubyapi.org/", target: "_blank" %>
      <p>
        Esta es la documentación oficial de la <code>API de Ruby</code>. En este recurso encontrarás todos los
        métodos y clases del lenguaje.Muy bien documentado, y fácil de navegar.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
</ul>
<h2>Recursos de terceros</h2>
<ul class="lista_links_ROR mt-5 mb-5">
  <li class="d-flex">
    <%= link_to "http://www.railsstatuscodes.com/ ", target: "_blank" do %>
      <%= image_tag  "http.svg", size: "75x75", class: "me-3"%>
    <%end%>
    <div>
      <%= link_to "Rails HTTP codes", "http://www.railsstatuscodes.com/ ", target: "_blank" %>
      <p>
        Aquí puedes consultar los <code>status codes</code> de HTTP. Es muy útil para
        saber qué significan los códigos que te devuelve el servidor. Además, incluye el nombre del helper correspondiente.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://rubygems.org/", target: "_blank" do %>
      <%= image_tag  "rubygems.svg", size: "75x75", class: "me-3"%>
    <%end%>
    <div>
      <%= link_to "Ruby Gems", "https://rubygems.org/", target: "_blank" %>
      <p>
        RubyGems es el repositorio oficial de <code>gemas de Ruby</code>. En este sitio encontrarás
        una gran cantidad de gemas que puedes utilizar en tus proyectos. Otro must.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://rubocop.org/", target: "_blank" do %>
      <%= image_tag  "rubocop.svg", size: "75x75", class: "me-3"%>
    <%end%>
    <div>
      <%= link_to "RuboCop", "https://rubocop.org/", target: "_blank" %>
      <p>
        RuboCop es un <code>linter</code> para Ruby. Es decir, es una herramienta que te ayuda a
        escribir código más limpio y legible. Además, te ayuda a seguir las mejores prácticas.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://rubystyle.guide/", target: "_blank" do %>
      <%= image_tag  "style_ruby.svg", size: "75x75", class: "me-3"%>
    <%end%>
    <div>
      <%= link_to "Guías de estilos Ruby", "https://rubystyle.guide/", target: "_blank" %>
      <p>
        Esta es una <code>guía de estilo para Ruby</code>. En ella encontrarás las mejores prácticas para
        escribir código limpio y legible. Además, te ayudará a seguir las convenciones de la comunidad.
      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
  <li class="d-flex">
    <%= link_to "https://toprubycompanies.info/ ", target: "_blank" do %>
      <%= image_tag  "top_rb.png", size: "75x75", class: "me-3"%>
    <%end%>
    <div>
      <%= link_to "Top Ruby Companies", "https://toprubycompanies.info/", target: "_blank" %>
      <p>
        Dicho por ellos mismos: "Descubra las principales <code>empresas de Ruby</code> en todo el mundo y vea el impacto del lenguaje de programación que se centra en la felicidad del desarrollador."      </p>
    </div>
  </li>
  <hr class="border border-danger border-1 opacity-50">
</ul>
<h2>
  Canales de Youtube
</h2>
<div class="row mt-5 mb-5">
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/c/GorailsTV", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "gorails.png" %>
        </div>
        <div class="p-3">
          <h3>Gorails</h3>
          <hr class="border border-danger border-1 opacity-50">
          En este canal encontrarás <code>tutoriales</code>, <code>tips</code> <code>guías</code>, y mucho más.
          Su creador, Chris Oliver, es un desarrollador de Ruby on Rails con más de 10 años de experiencia.
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@codewithpete508", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "pete.jpg" %>
        </div>
        <div class="p-3">
          <h3>Code with Pete</h3>
          <hr class="border border-danger border-1 opacity-50">
          Screencasts para desarrolladores web principiantes e intermedios que utilizan <code>Ruby on Rails</code>, <code>Hotwire</code> y <code>React</code>. Pete es un maestro excelente.
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@Webcrunch", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <svg viewBox="0 0 1907 1265" class="fill-current w-24 h-24 text-white pt-5" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M880.796 255.871H1026.21L953.5 380.738L880.796 255.871ZM81.0551 0H0L32.4515 55.7311L43.9544 75.4762L151.892 260.851L736.588 1265L953.5 892.471L1170.42 1265L1864.3 73.3448L1874.55 55.7416L1907 0.00668777H1825.95L1740.57 146.628L1667.21 272.625L1477.93 597.702L1170.42 1125.81L994.026 822.881L1061.97 706.204L1126.47 816.973L1170.42 892.458L1690.07 0.00668777H216.934L736.595 892.462L780.546 816.973L822.255 745.335L834.769 723.846L836.568 720.757L881.008 644.441L954.254 518.635L954.258 518.643L1103.83 261.765L1147.78 186.281H759.227L912.986 450.332L845.043 567.01L777.201 450.5L777.213 450.476L762.691 425.54L762.672 425.548L716.332 345.924L623.357 186.281H542.307L804.518 636.607L736.591 753.261L677.281 651.399L338.507 69.6034L716.987 69.6073L736.591 69.6034H1568.5L1229.73 651.395L1170.42 753.264L1102.49 636.607L1364.7 186.281H1283.66L736.591 1125.81L429.081 597.706L239.799 272.629L81.058 0.00668777L81.0551 0Z" fill="white"></path>
          </svg>
        </div>
        <div class="p-3">
          <h3>WebCrunch</h3>
          <hr class="border border-danger border-1 opacity-50">
          Web-Crunch es una web para el desarrollador, diseñador, empresario y creador web que aspira a resolver muchos de sus problemas con <code>diseño + código</code>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@mixandgo", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "m&g.png" %>
        </div>
        <div class="p-3">
          <h3>Mix & Go</h3>
          <hr class="border border-danger border-1 opacity-50">
          Cezar Halmagean es un desarrolador Web <code>especializado en Ruby on Rails</code>. Cuenta con más de <code>15 años de experiencia</code>, y su contenido es de mucha calidad. 
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@SupeRails", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "superrails.jpg" %>
        </div>
        <div class="p-3">
          <h3>SupeRails</h3>
          <hr class="border border-danger border-1 opacity-50">
          Características RoR, Tutoriales, Gemas, Stripe API, Serie Code-Along, Consejos y trucos, Algo de HTML y CSS. Sinceramente... <code>Un crack</code>.
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@DriftingRuby", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "drifting.png" %>
        </div>
        <div class="p-3">
          <h3>Drifting Ruby</h3>
          <hr class="border border-danger border-1 opacity-50">
          Drifting Ruby es otro imperdible. Cada video, es una avalancha de información sobre Rails y sus característica, con un <code>tono muy pragmático</code>.
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@cjav_dev", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "cj.png" %>
        </div>
        <div class="p-3">
          <h3>CJ Avilla</h3>
          <hr class="border border-danger border-1 opacity-50">
          Si quieres aprender a crear <code>aplicaciones web</code> e <code>integraciones de API</code>, este es tu canal. Además de Rails,comparte contenido de otros lenguajes.
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "https://www.youtube.com/@typefastco", target: "_blank" do %>
      <div class="card mb-3 d-flex flex-column tarjeta_yt">
        <div class="card_img mt-4 ms-4 me-4">
          <%= image_tag "typefast.png" %>
        </div>
        <div class="p-3">
          <h3>TypeFast</h3>
          <hr class="border border-danger border-1 opacity-50">
          Proyectos completos, de la talla de <code>AirBnb clone</code>, <code>Trello clone</code> y demás... Muy Muy bueno. Además está comenzando a compartir ,tutoriales, tips y guías.
        </div>
      </div>
    <% end %>
  </div>
</div>